{
  "embeddings": [
    {
      "tensorName": "My tensor",
      "tensorShape": [
        1000,
        50
      ],
      "tensorPath": "https://gist.github.com/.../tensors.tsv",
      "metadataPath": "https://gist.github.com/.../optional.metadata.tsv",
      "sprite": {
        "imagePath": "https://github.com/.../optional.sprite.png",
        "singleImageDim": [
          32,
          32
        ]
      }
    }
  ]
}