{
  "embeddings": [
    {
      "tensorName": "My tensor",
      "tensorShape": [
        755,
        2048
      ],
      "tensorPath": "https://gist.githubusercontent.com/won4113/e103d1aa243ef862fc7e5bf9c795d49a/raw/74971582ddd73df459c41a51d32d3305c545c379/ICON_Rox_Hard_desc.tsv",
      "metadataPath": "https://gist.githubusercontent.com/won4113/3f017b63aa2a624c5d893da51d8e3334/raw/b22184c1b60909a57ff1200d39fde807bcb0ac5e/ICON_Rox_Hard_label_new.tsv",
      "sprite": {
        "imagePath": "https://raw.githubusercontent.com/won4113/emb_viz/master/ICON_Rox_Hard_sprite_20.jpg",
        "singleImageDim": [
          20,
          20
        ]
      }
    }
  ]
}
